[enx]
dev-mode = true
port = 8090

[mysql]
address = "mysql.wiloon.com:3306"

[sync]
# minute
duration = 60

[news]
expire-time = "-720h"
gc-duration = "24h"

[log]
level = "debug"
path = "/data/rssx/logs/"
file-name = "rssx.log"

[youdao]
url = "https://openapi.youdao.com/api"
app-key = "567b022c76fd52ec"
app-secret = ""
